{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-paws
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paws_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paws/paws_{{ version }}.tar.gz
  sha256: 82f956e7a5df06f2fa300c8e82e433140b0ff1dc9287894d366bd306d49eeaf0

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-paws.analytics >=0.8.0
    - r-paws.application.integration >=0.8.0
    - r-paws.compute >=0.8.0
    - r-paws.cost.management >=0.8.0
    - r-paws.customer.engagement >=0.8.0
    - r-paws.database >=0.8.0
    - r-paws.developer.tools >=0.8.0
    - r-paws.end.user.computing >=0.8.0
    - r-paws.machine.learning >=0.8.0
    - r-paws.management >=0.8.0
    - r-paws.networking >=0.8.0
    - r-paws.security.identity >=0.8.0
    - r-paws.storage >=0.8.0
  run:
    - r-base
    - r-paws.analytics >=0.8.0
    - r-paws.application.integration >=0.8.0
    - r-paws.compute >=0.8.0
    - r-paws.cost.management >=0.8.0
    - r-paws.customer.engagement >=0.8.0
    - r-paws.database >=0.8.0
    - r-paws.developer.tools >=0.8.0
    - r-paws.end.user.computing >=0.8.0
    - r-paws.machine.learning >=0.8.0
    - r-paws.management >=0.8.0
    - r-paws.networking >=0.8.0
    - r-paws.security.identity >=0.8.0
    - r-paws.storage >=0.8.0

test:
  commands:
    - $R -e "library('paws')"           # [not win]
    - "\"%R%\" -e \"library('paws')\""  # [win]

about:
  home: https://github.com/paws-r/paws
  license: Apache-2.0
  summary: Interface to Amazon Web Services <https://aws.amazon.com>, including storage, database, and compute services, such as 'Simple Storage Service' ('S3'), 'DynamoDB' 'NoSQL' database, and 'Lambda' functions-as-a-service.
  license_family: APACHE
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - achimgaedke

# Package: paws
# Title: Amazon Web Services Software Development Kit
# Version: 0.1.12
# Authors@R: c(person(given = "David", family = "Kretch", role = c("aut", "cre"), email = "david.kretch@gmail.com"), person(given = "Adam", family = "Banker", role = "aut", email = "adam.banker39@gmail.com"), person(given = "Amazon.com, Inc.", role = "cph"))
# Description: Interface to Amazon Web Services <https://aws.amazon.com>, including storage, database, and compute services, such as 'Simple Storage Service' ('S3'), 'DynamoDB' 'NoSQL' database, and 'Lambda' functions-as-a-service.
# License: Apache License (>= 2.0)
# URL: https://github.com/paws-r/paws
# BugReports: https://github.com/paws-r/paws/issues
# Imports: paws.analytics (>= 0.1.12), paws.application.integration (>= 0.1.12), paws.compute (>= 0.1.12), paws.cost.management (>= 0.1.12), paws.customer.engagement (>= 0.1.12), paws.database (>= 0.1.12), paws.developer.tools (>= 0.1.12), paws.end.user.computing (>= 0.1.12), paws.machine.learning (>= 0.1.12), paws.management (>= 0.1.12), paws.networking (>= 0.1.12), paws.security.identity (>= 0.1.12), paws.storage (>= 0.1.12)
# Suggests: testthat
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-09-02 23:50:19 UTC; david.kretch
# Author: David Kretch [aut, cre], Adam Banker [aut], Amazon.com, Inc. [cph]
# Maintainer: David Kretch <david.kretch@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-09-03 04:50:11 UTC
